// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNwsqndlvWv0hexLO0m_7E1CFbDy_Bx9E',
    appId: '1:901434580101:web:67f3a06ffa95e65b1d1dec',
    messagingSenderId: '901434580101',
    projectId: 'flutter-test-550ad',
    authDomain: 'flutter-test-550ad.firebaseapp.com',
    storageBucket: 'flutter-test-550ad.appspot.com',
    measurementId: 'G-6LTBRD2212',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjOdb_IXyerEOwbHj-GdNhdKqx-6tF-4g',
    appId: '1:901434580101:android:1b2d50b3289cc67e1d1dec',
    messagingSenderId: '901434580101',
    projectId: 'flutter-test-550ad',
    storageBucket: 'flutter-test-550ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB367dFQ95-vXuktnrZEkOLeJ0Yq4xZYuQ',
    appId: '1:901434580101:ios:1cbacbf2669273881d1dec',
    messagingSenderId: '901434580101',
    projectId: 'flutter-test-550ad',
    storageBucket: 'flutter-test-550ad.appspot.com',
    iosBundleId: 'com.example.biciqrapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB367dFQ95-vXuktnrZEkOLeJ0Yq4xZYuQ',
    appId: '1:901434580101:ios:1cbacbf2669273881d1dec',
    messagingSenderId: '901434580101',
    projectId: 'flutter-test-550ad',
    storageBucket: 'flutter-test-550ad.appspot.com',
    iosBundleId: 'com.example.biciqrapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNwsqndlvWv0hexLO0m_7E1CFbDy_Bx9E',
    appId: '1:901434580101:web:043f4d01275d57341d1dec',
    messagingSenderId: '901434580101',
    projectId: 'flutter-test-550ad',
    authDomain: 'flutter-test-550ad.firebaseapp.com',
    storageBucket: 'flutter-test-550ad.appspot.com',
    measurementId: 'G-0K5Y3RKW8W',
  );
}
